# Generated by Django 4.1 on 2022-08-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=120)),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=120)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
